name: "Build Docker image"

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

env:
  RELEASE_VERSION: ${GITHUB_REF#refs/*/}

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push if the commit was to 'master'
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/riscv64
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/router_prometheus:master
      -
        name: Build and push if a tag was created
        if: ${{ env.RELEASE_VERSION }} != '' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/riscv64
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/router_prometheus:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/router_prometheus:${{ env.RELEASE_VERSION }}
